######################################################################
# Automatically generated by qmake (3.0) ?? ????. 19 19:41:27 2017
######################################################################

QT += widgets gui
TEMPLATE = app
TARGET = EasyContest
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
